### ISSUE TITLE
CLARIFICATION:- What limits the number of Inputs/Outputs

### ISSUE THREAD

**Issue by glenhawx** [sqall01/alertR#11]
I am sorry if this is the wrong medium on which to post this query. I'm trying to find out more about your project. I found you by searching for "Open Source Alarm System".
I want to start developing software on RasPi and I would like to update my home alarm system I figured I could try to kill two birds.
Not yet having experience with the RasPi I am at a disadvantage. I have a large gap in my knowledge.
How are the Inputs limited?
Can outputs be configured? I couldn't find reference to any beyond software and a siren.
Is there somewhere I can find out more information on the anatomy of the system?
Thanks for your time.

**Comment by sqall01** [comment]
Hi,

did you take a look at the [project wiki](https://github.com/sqall01/alertR/wiki) yet? There you find an explanation how the [alertR infrastructure](https://github.com/sqall01/alertR/wiki/infrastructure) works and other stuff like a basic configuration.

What do you mean with "How are the Inputs limited?". Do you mean the input GPIOs for sensors? If yes, they are not really limited. Well, if you only have "one" RaspberryPi in your setup, then they are limited by the number of GPIOs the RaspberryPi has. If you have "two" RaspberryPis in your setup, then twice the number. And so on (the sensor clients are responsible for that). Because alertR separated everything on a network level, you do not have a fix limitation on input sensors. I do not know when the limits of other resources are reached (like CPU usage on the server site and so on). But my setup is quite large with > 30 sensors on 5 different host systems and I do not have any problems yet.

What do you exactly mean with "Can outputs be configured?". Do you mean can you configure output GPIOs for a siren or something like that? If you mean that, yes you can (the alert clients are responsible for that). This will also be done by your RaspberryPi. I have uploaded a figure how you can use a siren with a RaspberryPi [here](https://github.com/sqall01/alertR/blob/master/docs/raspberry_pi_relais_switch.jpg). In the same directory there are also some other circuits you can use to connect stuff to the RaspberryPi.

I must admit, a more detailed tutorial on how to start and setup a basic setting is still missing and on my "to do" list. But I can not say when I will actually do it. It will be soon(TM) :smile:

**Comment by glenhawx** [comment]
Thanks heaps for your reply. I’ll try and clarify some question below…

> did you take a look at the project wiki <https://github.com/sqall01/alertR/wiki> yet? There you find an explanation how the alertR infrastructure <https://github.com/sqall01/alertR/wiki/infrastructure> works and other stuff like a basic configuration.

I did, I got an overall idea of the architecture of the system but I have never even touched an RPi yet.
> What do you mean with "How are the Inputs limited?". Do you mean the input GPIOs for sensors? If yes, they are not really limited. Well, if you only have "one" RaspberryPi in your setup, then they are limited by the number of GPIOs the RaspberryPi has. If you have "two" RaspberryPis in your setup, then twice the number. And so on (the sensor clients are responsible for that). Because alertR separated everything on a network level, you do not have a fix limitation on input sensors. I do not know when the limits of other resources are reached (like CPU usage on the server site and so on). But my setup is quite large with > 30 sensors on 5 different host systems and I do not have any problems yet.
> 
I guess a better question would be how many “input GPIOs” are there on a RPi?
I’m familiar with commercial alarm panels that have a main board with Xn inputs and Yn of outputs and then you can link expander panels to them for more inputs/outputs.
I take it that the sensors are wired directly into the RPi? Are GPIOs input lines for the RPi?
30 sensors on 5 different host systems… does that mean 5 RPi’s? 6 sensors on each?
Are you using anything else (eg. Arduino) to manage inputs?
> What do you exactly mean with "Can outputs be configured?". Do you mean can you configure output GPIOs for a siren or something like that? If you mean that, yes you can (the alert clients are responsible for that). This will also be done by your RaspberryPi. I have uploaded a figure how you can use a siren with a RaspberryPi here <https://github.com/sqall01/alertR/blob/master/docs/raspberry_pi_relais_switch.jpg>. In the same directory there are also some other circuits you can use to connect stuff to the RaspberryPi.
> 
On commercial alarm panels you can have relay outputs. You would have one for a siren but also others to trigger door locks or lighting or anything else you’d like to switch on or off.
From my limited experience with some micro controllers you can configure the different addresses to be either inputs or outputs so I was wondering if the RPi worked on the same principle.
Judging by your siren diagram it would appear that GPIOs are either inputs or outputs.
GPIO = General Purpose Input/Output?
> I must admit, a more detailed tutorial on how to start and setup a basic setting is still missing and on my "to do" list. But I can not say when I will actually do it. It will be soon(TM) 
> 
I wouldn’t worry too much I know it will be a steep learning curve for me. It always is when I start playing with a new device.

**Comment by sqall01** [comment]
> I did, I got an overall idea of the architecture of the system but I have never even touched an RPi yet.

If you never touched a Raspberry Pi and want to work with the GPIOs and
Python, I would recommend you the article "In Control" of the MagPi
Issue 2: <https://www.raspberrypi.org/magpi-issues/MagPi02.pdf>

> I guess a better question would be how many “input GPIOs” are there on a RPi?

Depends on the Raspberry Pi you are using. The normal Raspberry Pi B
model has 17 GPIO pins
<https://developer-blog.net/wp-content/uploads/2013/09/raspberry-pi-rev2-gpio-pinout.jpg>.
The B+ and 2 model have 26
<https://www.raspberrypi.org/documentation/usage/gpio-plus-and-raspi2/>.
(I ignore the Raspberry Pi Zero at the moment, since it is hard to get
it at the moment).

> I’m familiar with commercial alarm panels that have a main board with Xn inputs and Yn of outputs and then you can link expander panels to them for more inputs/outputs.

Each GPIO can be used as Input or as Output. So there is no distinction
between both (obviously, it should not be declared for both ;) ). I
think you can work also with expander modules here (with the I2C bus for
example). But I never did this. So I can not help you with this matter
unfortunately. Note, the architecture of alertR does not force you to
only work on a single Raspberry Pi. Because of the network
infrastructure, you can place different Raspberry Pis in your house that
work together (for example one RPi per floor).

> I take it that the sensors are wired directly into the RPi? Are GPIOs input lines for the RPi?

The sensors I use like motion detection and reed switches are directly
connected to the GPIOs with the circuits you find here
<https://github.com/sqall01/alertR/tree/master/docs>.

> 30 sensors on 5 different host systems… does that mean 5 RPi’s? 6 sensors on each?

No, see above ;) . And in my system there are not only "hardware"
sensors. For example, I check if the Internet connection is gone, if
unknown hosts connect to my WiFi, if one of my hosts is not reachable
and so on.

> Are you using anything else (eg. Arduino) to manage inputs?

Never tried it because I am not a good electronics guy. I am happy every
time something I am trying to build left the electronics/hardware area
and enters the software section ;) But since I found really cool stuff
for the Arduino like a Relais Board (German link)
<http://www.amazon.de/Kanal-Relay-Relais-Module-Arduino/dp/B00AEIDWXK/ref=sr_1_1?ie=UTF8&qid=1453128898#productDetails>,
I will definitely give it a try in the future.


> On commercial alarm panels you can have relay outputs. You would have one for a siren but also others to trigger door locks or lighting or anything else you’d like to switch on or off.
> From my limited experience with some micro controllers you can configure the different addresses to be either inputs or outputs so I was wondering if the RPi worked on the same principle.

Yes it does. See above and the MagPi Issue 2 :)

> Judging by your siren diagram it would appear that GPIOs are either inputs or outputs.
> GPIO = General Purpose Input/Output?

Correct.

> I wouldn’t worry too much I know it will be a steep learning curve for me. It always is when I start playing with a new device.

Hopefully my answers help.

**Comment by glenhawx** [comment]
Thanks heaps, mate.
I have been hacking around with Linux for the last 10-15 years, Arduino for the last 1-2 years and various other open source software (and some hardware) at the same time. It always amazes me how helpful people are. There is a reason why it is called a “community” and it’s great!!
I’m extremely close to buying a Pi2 (or a couple of them), I’ll definitely find time to give your project a go.
Thanks for the additional reading,
cheers,
Glen

**Comment by glenhawx** [comment]
Just found this...
https://learn.adafruit.com/reading-a-analog-in-and-controlling-audio-volume-with-the-raspberry-pi/connecting-the-cobbler-to-a-mcp3008

Analogue inputs would allow you to do tamper detection. You could run
end-of-line resistors and the analogue input would tell you if you had a
short or open circuit (intruder cut wires etc.)
Also 4 digital lines to monitor 8 analogue inputs!
