### ISSUE TITLE
alertClientExecuter, arguments and Node deactivate

### ISSUE THREAD

**Issue by cerikss8** [sqall01/alertR#19]
Hi! I have started a server with door switch, temp, cam and motion sensor and it have been running for a couple of months now, flawless!! great job. 
But now I will add a script to notify me thru a siren. How to use the executer with argument. Do you have a example!
I also have mail notification but via execute script thru external mail script, I would like to under stand how to use the alertClientMail and the built in mail templet. Do you have a example for that also.

PS: Is the plan for you to still implement the function for deactivate seperate nodes, great if so, I have a node in my sommer house for temperature and door sensor and want to deactivate it but still have my aparment active.

Keep up the good work!
Regards- Clas

**Comment by sqall01** [comment]
Hi,

thank you very much.

To use arguments in the executer client take a look at this tutorial: https://github.com/sqall01/alertR/wiki/Tutorial-AlertClientExecuter#tutorial_configuration_configfile_alerts

As you can see, it uses "/usr/bin/python" as a program to execute and "/home/alertr/alertClientExecuter/scripts/notify.py" and "start" as arguments. The <triggerArgument> is used for arguments that are passed when the alarm is triggered and <stopArgument> when the alarm is stopped. You can just add multiple <triggerArgument> or <stopArgument> to have multiple arguments passed to the program that is executed. They are passed in the order you define them.

Regarding the Mail client. I have not written a tutorial for it yet unfortunately. The client only works if you have a local SMTP server installed because I did not implement anything regarding SMTP authentication. An example email template is given here (should also be available when the client is installed): https://github.com/sqall01/alertR/blob/master/alertClientMail/config/example_template.mail Just enter your message there, add the keywords at the places you want the data to be (if you want any) and you are good to go. The rest of the client configuration is the same as for the other clients.

Yes, I still want to have "profiles" to disable stuff separately. But I do not know when I will start working on it. At the moment, I am working on push notification with an Android app. So when an alarm is triggered, you get a push notification to your Android devices. This will be the next part that will be finished.

Chers,

sqall
