### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by russellito** [sqall01/alertR#24]
Setting up server is failing for me. managerClientDatabase on localhost appears to be "running" as its log is updating every 5 seconds looking for a connection to the server.
Here is a cut from the Server.log
> 08/20/2017 21:58:08 ERROR: [storage.pyc]: Not able to get the unique id.
Traceback (most recent call last):
  File "/home/alertr/server/lib/storage.py", line 3442, in _getUniqueID
    self.uniqueID = self.cursor.fetchall()[0][0]
IndexError: tuple index out of range
08/20/2017 21:58:08 ERROR: [storage.pyc]: Not able to get node id.
Traceback (most recent call last):
  File "/home/alertr/server/lib/storage.py", line 5090, in getNodeId
    nodeId = self._getNodeId(username)
  File "/home/alertr/server/lib/storage.py", line 3361, in _getNodeId
    raise ValueError("Node id was not found.")
ValueError: Node id was not found.
08/20/2017 21:58:08 ERROR: [storage.pyc]: Not able to get node id.
Traceback (most recent call last):
  File "/home/alertr/server/lib/storage.py", line 4198, in addSensors
    nodeId = self._getNodeId(username)
  File "/home/alertr/server/lib/storage.py", line 3361, in _getNodeId
    raise ValueError("Node id was not found.")
ValueError: Node id was not found.
08/20/2017 21:58:08 ERROR: [alertRserver.py]: Could not parse config.
Traceback (most recent call last):
  File "/home/alertr/server/alertRserver.py", line 1412, in <module>
    + "to database.")
ValueError: Not able to add internal sensors to database. 

I've looked through wiki as much as I can and searched issues, even ran through the code lines noted  by errors to see if I could figure it out. I'm not very advanced though... any help you can give?

**Comment by russellito** [comment]
I should clarify, running alertRserver manually does start the server. I get these errors and don't see running status when trying to use systemd.

**Comment by sqall01** [comment]
Do you use MySQL or SQLite as backend for the server?

**Comment by russellito** [comment]
MySQL.

**Comment by sqall01** [comment]
> Is it saying that it can't get the ID for the alertRserver instance?
It looks like it. Normally the server should create an unique ID when it is started the first time and store it in the database. If a database already exists, then the unique ID is loaded from it. However, it seems that the server thinks the database exists but can not find the unique ID. It seems that your database is corrupt. 

Are the managerDatabase and the alertRserver using different databases? If they are using the same database they can end up corrupting each other. You can try deleting the database of the alertRserver and start it again. This gets the server instance to freshly setting up the database tables.

If the error still persists, can you please switch to the SQLite backend and see if there is an error like this? Then we can see if it is a configuration error on your site, an error in the MySQL part of the code or an general error in the code.

The MySQL backend for the alertRserver is actually not needed. Everything you want to do with the MySQL backend can be done by the managerDatabase instance (and it is the whole purpose of this manager). Because a lot of people seem to have problems to configure the MySQL backend correctly, I am thinking about dropping it completely for the alertRserver.

**Comment by russellito** [comment]
Oh, I figured they used  the same database. I guess I didn't follow instructions on the naming of the databases. I noticed they were different, shoot, my ignorance. I'll check that out tonight  and see if it works. I think thats the problem though. Thanks.

**Comment by russellito** [comment]
That was the problem. I really appreciate your help.
