### ISSUE TITLE
FIFO question = how to?!

### ISSUE THREAD

**Issue by cerikss8** [sqall01/alertR#28]
This is not an issue on it self but still a problem, I can't get the grip on how to implement the fifo sensor.
I have a smoke alarm that raise an alert on sensorclient by hard wired on to gpio.
My ide is to use a ESP32 (or Zero) to monitor the smoke alarm and have it write in to the fifo file to trigger a alert. But as I say in the beginning, I can't get the grip on how to. The truth is that I'm realy bad at fifo writing, never done it.
Do you have any example other then the example on the wiki?

-- Have you ever thought of having a upload page for all good examples and ideas of using the alertR system?!  
I have a setup where I use temp sensor and clientExecuter to sned MQTT to start and stop my heatpump during the winter months. 

//Clas

**Comment by sqall01** [comment]
The protocol for the FIFO is defined here: [https://github.com/sqall01/alertR/wiki/Protocol#protocol_schematics_fifo_sensor_sensoralert](https://github.com/sqall01/alertR/wiki/Protocol#protocol_schematics_fifo_sensor_sensoralert). There are also command lines to trigger an alert. But I think you already looked there.

In the `scripts_example` directory inside the installation there is the file [mac_address_whitelist.py](https://github.com/sqall01/alertR/blob/master/sensorClientFIFO/scripts_example/dhcpd_mac_address_whitelist/mac_address_whitelist.py) which contains also an example how to write into a FIFO file directly (actually, now when I see this I do not know why I did not use the json module ... definitely have to change this). 

When you would use the json module of python for this script it would look something like this:

```
import json

fifo_dict = dict()
fifo_dict["message"] = "sensoralert"

payload = dict()
payload["state"] = 1
payload["dataType"] = 0
payload["hasLatestData"] = False
payload["changeState"] = False
payload["hasOptionalData"] = True

optional_data = dict()
optional_data["message"] = "Something I want to tell someone."
payload["optionalData"] = optional_data

fifo_dict["payload"] = payload

with open("/your/fifo/file", 'w') as fifo_file:
    fifo_file.write(json.dumps(fifo_dict))
```

Is this sufficient for now? Or do you have problems somewhere else?

---

Regarding the upload page. I actually thought about it. For example I thought about creating a subreddit `alertr` for everyone who wants to post something alertr related like tutorials or cool setup ideas. Another idea I had was to create an AlertR misc github repository and anyone with something cool can add it there via a pull request. However, since no one seemed to be interested until now, I did not pursue it further. Personally I think the subreddit would be a better choice since it is like a internet forum software. What do you think?

Cheers
sqall

**Comment by sqall01** [comment]
Hi,

I added new Developer Tutorials to the [Tutorials list in the wiki](https://github.com/sqall01/alertR/wiki/Tutorials). The tutorial showing how to write a script for a FIFO sensor is placed [here](https://github.com/sqall01/alertR/wiki/Tutorial-Developer-SensorClientFIFOWrite)

Since this should answer your question, I will close this issue. However, if you have any further questions or a suggestion on the question of my last post post feel free to open it again.

Cheers
sqall

**Comment by cerikss8** [comment]
Hi!
Great! I'll take a peek on that and try to figure out how I can use
implement it.
AND!! thanx for the info earlier about the Fifo setup also.
Regarding a site for different alertR setups and smart implemention would
be a great ide', I think it is from that kind off sites alertR will start
to grow in user  number, specially when people can see it in action and get
ideas from working setups.

THX
CE

Den tis 19 juni 2018 kl 16:04 skrev Andre Pawlowski <
notifications@github.com>:

**Comment by sqall01** [comment]
Hey, just to let you know. I just created a [subreddit](https://www.reddit.com/r/AlertR/) where everyone can post there tutorials.

Cheers,
sqall
