### ISSUE TITLE
Error in sensorClientRaspberryPi interrupt callback

### ISSUE THREAD

**Issue by fgschaefer** [sqall01/alertR#37]
I tried to connect a PIR sensor today, but alertR did not react like i thought it should. The very first signal from the sensor after starting the client is always ignored and doesn't trigger even if `edgeCountBeforeTrigger` is set to `1`, because of this code (i think ;) ):
https://github.com/sqall01/alertR/blob/655f50bd1c5c2cf23ef8f3b504d9016105ae9cc3/sensorClientRaspberryPi/lib/sensor/interrupt.py#L68-L94
I have not thoroughly read the code and am just starting to get a grasp so maybe i'm wrong, but at a first glance i think everything after `# if edge counter reaches threshold` should be executed every time the method is called, and not only in the `else` branch.

**Comment by sqall01** [comment]
Yes you are right. I never noticed it when I was using this code with the door bell of my old apartment (since the signal was bouncing so much).

I fixed it by counting every time:
https://github.com/sqall01/alertR/blob/128b5c8181ed57a48cb42414fd0788822daadafb/sensorClientRaspberryPi/lib/sensor/interrupt.py#L68-L89

However, I have not used the interrupt sensor for years now and do not have any circuit here to test it. It would be great if you could check if the code works as expected since you are already testing the interrupt sensor. I will mark the issue as closed for now, but feel free to re-open it if something is not working as expected with the new code.

P.S.
Thank you for taking your time and checking the code. I really appreciate it :)

**Comment by fgschaefer** [comment]
I checked it, works as expected.
One question though: What is your strategy regarding new versions? Because i noticed the version number in `instanceInfo.json` files did not change after your last changes in the master branch, and so the version informer did not inform me of new versions ;)

Since i'm going to use the software, it is also in my interest to understand the code and make modest contributions. So thank YOU for making it available under a free software license :)

**Comment by sqall01** [comment]
> I checked it, works as expected.

Thanks for testing :)

> One question though: What is your strategy regarding new versions? Because i noticed the version number in `instanceInfo.json` files did not change after your last changes in the master branch, and so the version informer did not inform me of new versions ;)

Version numbers will normally change after modifications. See here for an explanation what which version/revision means: https://github.com/sqall01/alertR/wiki/Versioning
I did not change the version yet, because I have still one important fix for the master branch to ensure a flawless change to the dev branch as soon as I am finished there. Since the modifications to the master branch are not of such an importants that a user must directly have them, I wait a little longer so the user does not have to apply so many updates.

> Since i'm going to use the software, it is also in my interest to understand the code and make modest contributions. So thank YOU for making it available under a free software license :)

Thank you very much :) Can I ask how you found out about this project? Was it just "googling" or did you see it on some website?

**Comment by fgschaefer** [comment]
> Version numbers will normally change after modifications. See here for an explanation what which version/revision means: https://github.com/sqall01/alertR/wiki/Versioning

Ah i see, must have missed that wiki page. It looks like [Semantic Versioning](https://semver.org/) in a custom format.

> Can I ask how you found out about this project? Was it just "googling" or did you see it on some website?

I searched and found :)

**Comment by sqall01** [comment]
> Ah i see, must have missed that wiki page. It looks like [Semantic Versioning](https://semver.org/) in a custom format.
Yes. In hindsight not a smart move to do a custom format. But now changing it would create several problems.
