### ISSUE TITLE
What is the most simple way to activate/deactivate alertR time-controlled?

### ISSUE THREAD

**Issue by fgschaefer** [sqall01/alertR#38]
Sorry if i'm missing something here, but i did not find a minimalistic way to activate and/or deactivate the alarm system with e.g. a cron-job or something like that.
Do i have to use the managerClientDatabase for this, even if i don't need the database?

**Comment by sqall01** [comment]
Unfortunately, the managerClientDatabase is at the moment the only way to do it without modifying the code of AlertR. This is really bad, because you have to run a whole MySQL DB installation even if you do not need it.

However, on my short term agenda is manager client that will make this easier (more specifically a manager client with a REST API). But I do not know when it will be finished. This always depends on my free time and more importantly on my motivation (which is at the moment at a low). My guess is it will take a couple of months until I start working on it.

**Comment by fgschaefer** [comment]
Well no problem then, just wanted to know if i missed something essential. Expanding code is always a valid option i think ;)

I don't have much time at the moment, but i think some playing around would be possible for me as a first step, maybe a temporary solution until something proper is available.
If i wanted to build a new manager client, how would i start?
I noticed a managerClientTemplate in the dev branch, is this a valid starting point?

**Comment by sqall01** [comment]
Yes, the managerClientTemplate is a good starting point. This will also become the base for the already existing manager clients to make everything more maintainable.

**Comment by fgschaefer** [comment]
Great, thanks. I'll see if i have some time to look into it a little bit.

Meanwhile I decided to take the "simpler" path of using the managerClientDatabase, because after thinking about it for a while a little web frontend could be of use after all, so the database client would already be there to also be used for time scheduled activation/deactivation.

**Comment by qpaz** [comment]
@fgschaefer
i have solved it with a cronjob on managerClientDatabase

15 4	* * 1,2,3,4,5	root	/usr/bin/php /var/www/alertr/schAlarm.php 0
0 9	* * 1,2,3,4,5	root	/usr/bin/php /var/www/alertr/schAlarm.php 1

[schAlarm.php.txt](https://github.com/sqall01/alertR/files/5409922/schAlarm.php.txt)

**Comment by fgschaefer** [comment]
@qpaz 
Yes that's how i solved it too, just with a bash script called the same way by cron like your php file:
`#!/bin/bash
echo "{\"message\": \"option\", \"payload\": {\"optionType\": \"alertSystemActive\", \"value\": $1, \"timeDelay\": 0}}"  | socat - UNIX-CONNECT:/home/alertr/local.socket`
