### ISSUE TITLE
ManagerClientConsole cant find server 

### ISSUE THREAD

**Issue by ScrapyHD** [sqall01/alertR#39]
both the server and managerclientconsole are configured as the tutorial and run on port:44556, client has server as localhost and in the log it says it cannot find the alertRserver when it is running on the same machine (virtual machine, ubuntu 20.0.4) 

Here's the log:
06/20/2020 00:45:03 ERROR: [alertRclient.py]: Could not parse config.
Traceback (most recent call last):
  File "alertRclient.py", line 137, in <module>
    raise ValueError("Server CA does not exist.")
ValueError: Server CA does not exist.

**Comment by sqall01** [comment]
Actually, it is not at the point where it tries to reach the server. It says it cannot parse the configuration file because your server CA file does not exist.

This is the file that you configure under <server [...] caFile="<PATH HERE>" /> in the config file of the client. My guess is, you did not copy the certificate file created for your server to the correct location as described here: [Manager Client Console Tutorial - Certificates](https://github.com/sqall01/alertR/wiki/Tutorial-ManagerClientConsole#tutorial_configuration_cert)

**Comment by ScrapyHD** [comment]
i checked the config and it is in the correct location
this is what i have in the config:
<server
            host="localhost"
            port="44556"
            caFile="home/alertr/managerClientConsole/config/alertr_server.crt" />

**Comment by sqall01** [comment]
Hi,

judging from the code you provide, your file is not found because you are missing the leading "/" in the beginning of the path. Therefore, you are not using an absolute path but a relative one from the directory you installed the AlertR client.

To be more precise: your configuration `home/alertr/managerClientConsole/config/alertr_server.crt` would search the certificate at `/home/alertr/managerClientConsole/home/alertr/managerClientConsole/config/alertr_server.crt` (assuming you installed the client under `/home/alertr/managerClientConsole`.
The correct setting would be `/home/alertr/managerClientConsole/config/alertr_server.crt` since it would then search directly there.

Cheers,
sqall

**Comment by ScrapyHD** [comment]
wow... i had a problem with the config before and a missing slash was the exact issue, man i should've thought/checked that. Thank you for the help and i apologize for the annoyance!

**Comment by sqall01** [comment]
No hard feelings. These things can happen :)
