### ISSUE TITLE
Best way to implement a door sensor 

### ISSUE THREAD

**Issue by ScrapyHD** [sqall01/alertR#40]
I have been looking around and it looks like there is no way to implement the smart sensors that you can generally buy, and now i'm looking at making a sensor with a pi zero w, reed switch, and a battery but im wondering if there is a simpler solution/implementation anyone has figured out, if there is please let me know, thanks!

**Comment by sqall01** [comment]
I actually never looked at any "smart sensor" (I guess you mean these wireless sensors at doors and windows?) because I use cables for the sensors. Hence, I do not know how well you can communicate with them with a Raspberry Pi or something else to integrate them into AlertR.

The only wireless sensor switch idea I saw was here: [http://projects.privateeyepi.com/home/home-alarm-system-project/wireless-projects/wireless-switch-2-0](http://projects.privateeyepi.com/home/home-alarm-system-project/wireless-projects/wireless-switch-2-0). The PrivateEye Pi guys have some nice hardware ideas for a Raspberry Pi system on their website. However, last time I checked the code they provide was ... let us just say it was not so good. [I wrote a blog article about some things that I found a few years ago.](https://h4des.org/blog/index.php?/archives/353-Security-Issues-in-PrivateEyePi-Home-Alarm-System-Why-I-would-not-use-it!.html).

I like the idea using a Pi Zero with WiFi and am curious what you will come up with. Perhaps you are willing to share your creation in form of a tutorial or documentation?

Just as a side note: Personally, I would not use the wireless sensor part because it can be easily bypassed by jamming. But this goes for almost all commercial products as well (either you just jam the frequency completely or in intervals so that the jamming detection would not go off but the intervals are too short to actually get a signal through). My guess is that this is the reason that the alarm systems I saw used in the industry that are certified for a more security related area all use cables for the sensor connections.

**Comment by ScrapyHD** [comment]
i see, i understand that a wireless component adds security loopholes and places the entire system at risk however in my case i dont have any other options as running wires would require me to open up my walls and even if i decided to go with the cables visible alongside the walls there isn't an outlet or Ethernet jack for a good amount of distance. I will definitely put up a tutorial with my creation and findings, thanks for the info and help!

**Comment by ScrapyHD** [comment]
i finally cobbled everything together but i'm having an issue connecting the raspberrypi client to the server, its throwing a connection refused error :
![IMG_5286](https://user-images.githubusercontent.com/67180350/86194602-eabdb100-bb1c-11ea-840e-4910a43d8829.jpg)

Any idea why? Its configured as the tutorial instructs and i double checked the manageusers and the credentials are correct

**Comment by sqall01** [comment]
Do you use the correct server address and port? Can you reach the server port manually with telnet or nc from the client? What do the logs on the server say? The shown output usually occurs if the server is not reachable.

**Comment by ScrapyHD** [comment]
Right now i have the server address set to localhost and port to 44556 as in the tutorial config

the server log:
07/01/2020 01:56:03 DEBUG: [connection.py]: Acquire node timeout sensor lock.
07/01/2020 01:56:03 DEBUG: [connection.py]: Release node timeout sensor lock.
07/01/2020 01:56:03 DEBUG: [sqlite.py]: Acquire lock.
07/01/2020 01:56:03 DEBUG: [sqlite.py]: Release lock.
07/01/2020 01:56:03 DEBUG: [sqlite.py]: Acquire lock.
07/01/2020 01:56:03 DEBUG: [sqlite.py]: Release lock.
07/01/2020 01:56:03 DEBUG: [sqlite.py]: Acquire lock.
07/01/2020 01:56:03 DEBUG: [sqlite.py]: Release lock.
07/01/2020 01:56:03 DEBUG: [sqlite.py]: Acquire lock.
07/01/2020 01:56:03 DEBUG: [sqlite.py]: Release lock.
07/01/2020 01:56:03 DEBUG: [sqlite.py]: Acquire lock.
07/01/2020 01:56:03 DEBUG: [sqlite.py]: Release lock.
07/01/2020 01:56:03 DEBUG: [server.py]: Release lock (127.0.0.1:39028).
07/01/2020 01:56:04 DEBUG: [server.py]: Acquire lock (127.0.0.1:39028).
07/01/2020 01:56:04 DEBUG: [server.py]: Release lock (127.0.0.1:39028).
07/01/2020 01:56:05 DEBUG: [server.py]: Acquire lock (127.0.0.1:39028).
07/01/2020 01:56:05 DEBUG: [server.py]: Release lock (127.0.0.1:39028).
07/01/2020 01:56:06 DEBUG: [server.py]: Acquire lock (127.0.0.1:39028).
07/01/2020 01:56:06 DEBUG: [server.py]: Release lock (127.0.0.1:39028).
07/01/2020 01:56:07 DEBUG: [server.py]: Acquire lock (127.0.0.1:39028).
07/01/2020 01:56:07 DEBUG: [server.py]: Release lock (127.0.0.1:39028).
07/01/2020 01:56:08 DEBUG: [server.py]: Acquire lock (127.0.0.1:39028).
07/01/2020 01:56:08 DEBUG: [sqlite.py]: Acquire lock.
07/01/2020 01:56:08 DEBUG: [sqlite.py]: Release lock.
07/01/2020 01:56:08 DEBUG: [connection.py]: Acquire node timeout sensor lock.
07/01/2020 01:56:08 DEBUG: [connection.py]: Release node timeout sensor lock.
07/01/2020 01:56:08 DEBUG: [sqlite.py]: Acquire lock.
07/01/2020 01:56:08 DEBUG: [sqlite.py]: Release lock.
07/01/2020 01:56:08 DEBUG: [sqlite.py]: Acquire lock.
07/01/2020 01:56:08 DEBUG: [sqlite.py]: Release lock.
07/01/2020 01:56:08 DEBUG: [sqlite.py]: Acquire lock.
07/01/2020 01:56:08 DEBUG: [sqlite.py]: Release lock.
07/01/2020 01:56:08 DEBUG: [sqlite.py]: Acquire lock.
07/01/2020 01:56:08 DEBUG: [sqlite.py]: Release lock.
07/01/2020 01:56:08 DEBUG: [sqlite.py]: Acquire lock.
07/01/2020 01:56:08 DEBUG: [sqlite.py]: Release lock.
07/01/2020 01:56:08 DEBUG: [server.py]: Release lock (127.0.0.1:39028).
07/01/2020 01:56:09 DEBUG: [server.py]: Acquire lock (127.0.0.1:39028).
07/01/2020 01:56:09 DEBUG: [server.py]: Release lock (127.0.0.1:39028).
07/01/2020 01:56:10 DEBUG: [server.py]: Acquire lock (127.0.0.1:39028).

**Comment by ScrapyHD** [comment]
does it have to be a specific ip if its not running on the same host computer?

**Comment by sqall01** [comment]
The client has to have the correct IP address of the server. If you just enter localhost (127.0.0.1) and the server is not running on the same host, it cannot connect to it (obviously, since it does not know where the server is running).

If this was the case of your error and you do not understand why, I would suggest to first start with fundementals of networking. Otherwise you will not have much fun with AlertR since you will run in one error after the next since it is not meant to be a "one click solves everything automatically product".

**Comment by ScrapyHD** [comment]
i understand, for some reason i was thinking that the localhost would apply over the network (i had something like this in another project however it wasn't running on linux). Turns out it was a combination of not setting the correct ip in the config and having VirtualBox's network adapter in NAT mode instead of Bridge mode
