### ISSUE TITLE
Feature request: allow the use of IMAP IDLE for push notifications

### ISSUE THREAD

**Issue by tbertels** [sqall01/alertR#41]
[IMAP IDLE](https://en.wikipedia.org/wiki/IMAP_IDLE), unlike most push implementations, is an open specification ([RFC 2177](https://tools.ietf.org/html/rfc2177)), supported by a number of email servers.
If the user already has an account on one of them, no new registering is required.
AlertR and its app could allow the use of IMAP IDLE. The app would check if the server supports it by sending the CAPABILITY command.

**Comment by sqall01** [comment]
I personally do not see the benefit for it (despite supporting devices not having Google Play Services installed). So I do not think I will work on this one. However, since this is an open source project, everyone can feel free to work on this part if this feature is wanted. But if someone does, please coordinate with me so we can go in the same direction when it comes to the rewrite of the AlertR app.

**Comment by sqall01** [comment]
Closing these issue because of no responses.
