### ISSUE TITLE
Triggered alert before system active didnt gets triggered again

### ISSUE THREAD

**Issue by qpaz** [sqall01/alertR#46]
i have magnetic switches and the sensorClientRaspberryPi installed. the alertClientExecuter makes a phone call if the system is active and an alert is triggered. but when the alert was triggered before the system gets activated, it didnt gets triggered again. e.g. "the kids" forgot to close the garage before the system gets activated.
is there an overseen config item to this scenario?

**Comment by sqall01** [comment]
So only that I understand the scenario correctly. You have the following:

sensorClientRaspberryPi -> server -> alertClientExecuter

What happened was the following:

1. Alarm System Deactivated (was already deactivated)
2. sensorClientRaspberryPi triggered sensor alert
3. server processed sensor alert but did nothing since alarm system is deactivated
4. Alarm System Activated
5. sensorClientRaspberryPi triggered sensor alert
6. server processed sensor alert BUT NOTHING HAPPENED (here we have the problem)

Is this timely order correct?

Then I have still a few questions:

- Can you paste the configuration parts of the Sensor involved in this?
- Can you paste the configuration parts of the Alert Levels involved in this?
- Can you paste the configuration parts of the Alert involved in this?
- Can you reproduce this behavior?

**Comment by qpaz** [comment]
Not exactly, thanks for recap this. 
forget the steps 5. 6. 7. its working perfect in that manner, because garage was closed and openend again and so the trigger is processed in active state. 

but at step 4, shouldn't the server execute an alert with alertClientExecuter because of a sensor which is already in triggered state?

`
sensorClientRaspberryPi config
`

       <sensor>
            <general
                id="1"
                description="Garage"
                alertDelay="0"
                triggerAlert="True"
                triggerAlertNormal="False" />
            <alertLevel>0</alertLevel>
            <alertLevel>1</alertLevel>
            <gpio
                type="polling"
                gpioPin="7"
                triggerState="1"
                stateCounter="2" />
        </sensor>
`
server config
` 

       <alertLevel>
            <general
                level="0"
                name="display notification"
                triggerAlways="True"
                triggerAlertTriggered="True"
                triggerAlertNormal="True" />
            <rules
                activated="False">
            </rules>
        </alertLevel>
        <alertLevel>
                level="1"
                name="alarm"
                triggerAlways="False"
                triggerAlertTriggered="True"
                triggerAlertNormal="False"  />
            <rules
                activated="False">
            </rules>
        </alertLevel>
`
alertClientExecuter config
`

       <alert>
            <general
                id="0"
                description="PhoneCall To Master" />
            <alertLevel>1</alertLevel>
            <executer
                execute="/usr/bin/python2">
                <triggered
                    activated="True">
                    <argument>/opt/alertr/alertClientExecuter/lib/callMe.py</argument>
                    <argument>start</argument>
                </triggered>
                <normal
                    activated="False">
                    <argument>arg1</argument>
                    <argument>arg2</argument>
                </normal>
                <off
                    activated="False">
                    <argument>arg1</argument>
                    <argument>arg2</argument>
            </executer>
        </alert>
`

**Comment by sqall01** [comment]
> but at step 4, shouldn't the server execute an alert with alertClientExecuter because of a sensor which is already in triggered state?

No, it should not. AlertR works event based. Meaning the change of a sensor state (for example opening the garage door or closing it) is processed. An already processed state, in your case the open garage door, is not processed again if you activate the alarm system. This for example allows you to open the windows in a summer night to get some fresh air before going to bed and leaving them open while you activate the alarm system. Only when you close them AlertR is interested in the state change if opening them again.

Since in your case someone forgot to close the garage door: I do not know if you use the mangerClientKeypad, but it has a [setting](https://github.com/sqall01/alertR/blob/master/managerClientKeypad/config/config.xml.template#L178) which allows you to configure sensor states which are checked before it will activate the alarm system. For example, you could configure the manager to check if the garage door is closed. If it is not, it will display you a warning and ask for your confirmation to activate the alarm system. However, this works only locally on the manager client itself if you use it to activate the alarm system and not globally (for example, you use another way to activate the alarm system as a web page). In my home, I have the mangerClientKeypad running next to my front door and use it to activate the alarm system when I am leaving. Each time I use it, the manager checks each window in my home for the correct state and therefore I get reminded if I forgot to close one.

**Comment by qpaz** [comment]
ok, got it.... thanks for your explanation, support and solution. appreciate that.
but since iam running the cronjob to activate and deactivate the alarm system, i have to figure out something else to check if the sensors are all in the correct state at activation.

**Comment by sqall01** [comment]
Just as an idea. Alarm system activation and deactivation trigger also a sensor alert with the internal server sensor "alertSystemActive". Perhaps when the alarm system gets activated, you could use the sensor alert to execute a script with the help of the alertClientExecuter. This script could check a mysql database (which holds all the AlertR system data with the help of the managerClientDatabase) for the state your specific sensors are in. If they are not in the state you want, you could react in any way you like (even create another sensor alert in the AlertR system with the help of the sensorClientFIFO as explained in this [developer tutorial for instrumentation](https://github.com/sqall01/alertR/wiki/Tutorial-Developer-InstrumentSensorAlerts)).

Just a quick idea or food for thought for you :)
