### ISSUE TITLE
Problem with alertwebmobilemanager after update to 0.800

### ISSUE THREAD

**Issue by cerikss8** [sqall01/alertR#47]
Hi!
After update to 0.800 on server and different clients I can't connect to the webmanager or rather the webpage stop loading, it's only rendering the loading gif. After updating the server/client I forgot to update the webmanager (index,config.php etc) and the webpage did load but with no activation buttons and so on. After updating all web stuff it only shows the loader gif.
Have I forgot some permissions or what? 
The tutorial for webmobilemananger is removed and I can't really remember how it was setup in the beginning  

/Clas

**Comment by sqall01** [comment]
Hi,
you have to update the whole content of the webmanager since a lot has changed there (main.js, index.php and so on).

Further, did you configure the Profiles in your AlertR Server configuration correctly? With version 0.800, the "activated" and "deactivated" state was removed. You now have to use Profiles if you want this state back (in your case, creating a Profile called "activated" and a Profile called "deactivated"). I described the change [here](https://www.reddit.com/r/AlertR/comments/lkans4/version_0800_released/) and further all tutorials in the Wiki now explain what to configure regarding the Profiles (see the [Server tutorial](https://github.com/sqall01/alertR/wiki/Tutorial-Server) for example).

Cheers
sqall

**Comment by cerikss8** [comment]
Hi!
Yes, I have configured Profiles and I can run the the system through Consolmanager, switch Profiles and so on, all fine. 
I think I have changed all content in the webmanager, I will check,  but I can’t remember if I have to change owner or permissions on some of the files in the www/ folder!? and the web tutorial seems to be removed from the repository. Or I might just be crappy searcher.
The idea of implement Profiles to the system is great and it makes the system more flexible.

Cheers 
Clas

Skickat från min iPhone

**Comment by sqall01** [comment]
Thanks. It is great feedback to hear that you like it.

Can you please make sure that the file are updated to the new ones in the repository. The config.php did not change, therefore you can use the old one here. I just checked everything in my installation at home and it works.

The old example configuration file was deleted from the wiki. But since the wiki on github is just another git repository, it is not gone. I attached it as a zip file to this comment (since .md is not supported to upload :shrug: ).

[Example-Configuration.md.zip](https://github.com/sqall01/alertR/files/6136219/Example-Configuration.md.zip)

**Comment by sqall01** [comment]
I close this issue since no response is given.
