### ISSUE TITLE
Feature Request: Alert Level - Administrative Enable/Disable

### ISSUE THREAD

**Issue by akkord64** [sqall01/alertR#5]
Have the ability to disable/enable alert level categories individually using a security PIN

ie - Enable the Home alarm system (lvl2) separately then the Fire system -(lvl1) and turn off that unreliable sensor I am working on in the garden (lvl50)

**Comment by qpaz** [comment]
is the project still alive? just want to ask when maybe this feature is added? love the arch, proto and functionality of alertr. great one.

**Comment by sqall01** [comment]
First of all, thanks for your kind words. This is what helps to motivate :)

Yes, this project is very much alive. I know Github only shows the commits for the "master" branch on the main page, but the "dev" branch is very active.

When this feature is added? Hard to tell.

My agenda is as follows:
1) At the moment I am working on version 0.4 of alertR and hope to release it in about 2 months. This version will have new features like internal sensors for the server (to have a triggered alarm if a sensor times out, a node disconnects and so on) and sensors that can handle data (like temperature sensors, brightness sensors, and so on).
2) After the release I will update the wiki and will add new tutorials and a better presentation of this project.
3) I have a rough design idea for a new central component that should make interaction with mobile devices easier (I will publish more details when I have a concept). I think this is the part I will slowly start to work on after that.
4) The profile feature for version 0.5

So, roughly I would guess end of the year. I would like to have this feature, but my guess is that it will require some rewriting of the rule engine (which is good, because the rule engine needs to be refactored). So it is not a top priority at the moment, sorry.

**Comment by sqall01** [comment]
Closing these issue because of no responses.
