### ISSUE TITLE
PHP issues with Web Mobile manager

### ISSUE THREAD

**Issue by cerikss8** [sqall01/alertR#51]
Hi!
I'v deployed AlertR 0.900 on a AWS instance with Ubuntu 20.04 and I have problem with the web page rendering. The Apache server do display the index.php but there is no buttons for changing the profiles, the global php version is 8.0.12 and enabled version in Apache2 is the same.
I'v tryed to enable php5.6 but then it is only the loading icon showing up on screen.
On my server at home I have 0.800 on Debian 11 with php 5.6 enabled and all is running fine
Is there any known extensions needed?!
Update!
I disabled the php8..0 and enabled the 5.6 and  I saw on the webpage that the Apache lost the connection to the database... hmmm

//Clas

**Comment by sqall01** [comment]
This is actually quite strange. I do not think it has anything to do with PHP because the actual interfaces is generated with JS and since you say you see other parts on the interface, there is something fishy.

Could you please provide me with a screenshot so that I can see how the interface looks exactly? The only reason I could see with a quick glance over the code is, that the JS code does not find the "profile" entry in the options. Then the buttons would not appear.

Furthermore, could you please access the getJson.php file on your web server via browser with the following parameters:

`getJson.php?data[]=internals&data[]=options&data[]=profiles&data[]=nodes&data[]=sensorAlerts&sensorAlertsRangeStart=0&sensorAlertsNumber=10&data[]=sensors`

Can you then post the data you get shown in your browser? This is the data that is requested from the database by the index.php file when you access it initially.

Just as a disclaimer, at the moment I have a lot on my plate. Hence, my responses to this issue could be quite delayed.

And on a personal note: I am always curious what AlertR is used for by others. You are the first one I heard of that installed it in the cloud on an AWS instance. Do you mind actually telling me what you are planing to do with it in the cloud?

Cheers
sqall

**Comment by cerikss8** [comment]
Hi!
Here's a screen shot:
[image: image.png]
But the thing you ask me to do with the getJson I din't get...how and
where?! sorry!


When I tail the error.log I get:
[Fri Nov 05 00:00:01.190673 2021] [mpm_prefork:notice] [pid 51084] AH00163:
Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f configured -- resuming normal
operations [Fri Nov 05 00:00:01.190694 2021] [core:notice] [pid 51084]
AH00094: Command line: '/usr/sbin/apache2' [Fri Nov 05 06:19:46.381428
2021] [core:error] [pid 52758] [client 45.146.164.110:36162] AH00126:
Invalid URI in request POST /cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh HTTP/1.1
[Fri Nov 05 06:58:35.869883 2021] [mpm_prefork:notice] [pid 51084] AH00169:
caught SIGTERM, shutting down

My ide' on using AWS is that I will not need a fysical server that can
break down and so on. And I see that it's much easier to make pre-make
sensors and other stuff and deploy it later up to AWS, example- I have
installed AlertR at my daughter house and I can pre-make all setup at home
and later on and install it at her home, I dont need to know there IP-
address and password to router's and so on. And I can manage the system
remote more or less with direct access to sensors via AWS.
In my sommer house we have 4g over NAT so I can reach the external IP
without tunneling, but with AWS I have possibilities to set a DNS and can
also SSH vai AWS console to all sensors

/CE

Den fre 5 nov. 2021 kl 09:28 skrev Andre Pawlowski ***@***.***

**Comment by cerikss8** [comment]
Hi again!!
Now I've switched from php8 to php5.6 on the AWS instance, because php5.6
is what I'm using at my server at home and it is working perfectly, with
0.800 conf.
The webpage is as I mentioned earlier get stuck on loading icon but this is
what the Apache log prints out:
 [Fri Nov 05 14:16:03.173895 2021] [:error] [pid 63777] [client
89.160.31.253:34484] PHP Warning:  mysqli::mysqli(): (HY000/2054): The
server requested authentication method unknown to the client in
/var/www/alertr/getJson.php on line 44, referer:
https://nano-jetson.duckdns.org/

You can go to https://nano-jetson.duckdns.org/ and see it. I give your
access- user:sqall pwd:sqall


PS:
I'm also using AlertR at work as a monitoring system for checking the state
of the security gates and pumps etc. I'm working at the port as Port
Engineer/Port Operations Manager. I use 0.600 on a server on premises, due
to ISPS regulations it running only locally

//Clas


Den fre 5 nov. 2021 kl 12:35 skrev Clas Eriksson ***@***.***>:

**Comment by cerikss8** [comment]
Back on php8.0 now, really annoying :-(

Den fre 5 nov. 2021 kl 15:46 skrev Clas Eriksson ***@***.***>:

**Comment by cerikss8** [comment]
Hi! Sorry for bothering you!
But now I know what I did wrong!!
I made a spelling error in config.php and also my path to local.socket was
without a / in the beginning... sh*t!
That's why it's only displayed it as viewport with no control buttons
Now it's running with AlertR 0.900 and php7
So issue 51 can be closed

// Chears
CE

Den fre 5 nov. 2021 kl 19:07 skrev Clas Eriksson ***@***.***>:

**Comment by cerikss8** [comment]
Root cause of problem was typo
